### ISSUE TITLE
Plugins not importing successfully

### ISSUE THREAD

**Issue by BusiWork** [GoogleCloudPlatform/healthcare-data-harmonization#78]
I am following the Getting Started tutorial, and there is mention of logging. However, if I add a logging import as follows to my whistle file:

import "class://com.google.cloud.verticals.foundations.dataharmonization.plugins.logging.LoggingPlugin"

Gradle run throws an ImportException:

Exception in thread "main" java.lang.NullPointerException
        at com.google.cloud.verticals.foundations.dataharmonization.imports.ImportPath.resolve(ImportPath.java:104)
        at com.google.cloud.verticals.foundations.dataharmonization.imports.impl.DefaultImportProcessor.processImports(DefaultImportProcessor.java:92)
        at com.google.cloud.verticals.foundations.dataharmonization.imports.impl.DefaultImportProcessor.processImports(DefaultImportProcessor.java:62)
        at com.google.cloud.verticals.foundations.dataharmonization.imports.impl.ProtoParserBase.parseConfig(ProtoParserBase.java:88)
        at com.google.cloud.verticals.foundations.dataharmonization.init.initializer.ConfigExtractorBase.initialize(ConfigExtractorBase.java:58)
        at com.google.cloud.verticals.foundations.dataharmonization.init.Engine$Builder.initialize(Engine.java:302)
        at com.google.cloud.verticals.foundations.dataharmonization.init.Engine$Builder.initialize(Engine.java:325)
        at com.google.cloud.verticals.foundations.dataharmonization.Main.main(Main.java:120)

Is there a step I am missing?

**Comment by BusiWork** [comment]
The error varies depending on where my whistle files are. Above reported error is when wstl file is in the runtime directory but if I run from the root directory I get the following error:

`Exception in thread "main" com.google.cloud.verticals.foundations.dataharmonization.exceptions.ImportException: Error processing import class:///com.google.cloud.verticals.foundations.dataharmonization.plugins.logging.LoggingPlugin
Class not found: com.google.cloud.verticals.foundations.dataharmonization.plugins.logging.LoggingPlugin. Make sure it is in the current classpath.
        at com.google.cloud.verticals.foundations.dataharmonization.imports.impl.DefaultImportProcessor.processImports(DefaultImportProcessor.java:116)
        at com.google.cloud.verticals.foundations.dataharmonization.imports.impl.DefaultImportProcessor.processImports(DefaultImportProcessor.java:62)
        at com.google.cloud.verticals.foundations.dataharmonization.imports.impl.ProtoParserBase.parseConfig(ProtoParserBase.java:88)
        at com.google.cloud.verticals.foundations.dataharmonization.init.initializer.ConfigExtractorBase.initialize(ConfigExtractorBase.java:58)
        at com.google.cloud.verticals.foundations.dataharmonization.init.Engine$Builder.initialize(Engine.java:302)
        at com.google.cloud.verticals.foundations.dataharmonization.init.Engine$Builder.initialize(Engine.java:325)
        at com.google.cloud.verticals.foundations.dataharmonization.Main.main(Main.java:120)
Caused by: java.io.IOException: Class not found: com.google.cloud.verticals.foundations.dataharmonization.plugins.logging.LoggingPlugin. Make sure it is in the current classpath.
        at com.google.cloud.verticals.foundations.dataharmonization.imports.impl.PluginClassLoader.load(PluginClassLoader.java:44)
        at com.google.cloud.verticals.foundations.dataharmonization.imports.impl.DefaultImportProcessor.processImports(DefaultImportProcessor.java:109)
        ... 6 more
`
